# Generated by Django 3.2.5 on 2021-07-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210716_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='ISBN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='Year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='bookauthor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='bookname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
