# Generated by Django 3.2.5 on 2021-07-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210717_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbook',
            name='active',
        ),
        migrations.AddField(
            model_name='addbook',
            name='available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addbook',
            name='borrowing_period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
