# Generated by Django 3.2.5 on 2021-07-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210718_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='borrower',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
