# Generated by Django 3.2.5 on 2021-07-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_addbook_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Student', 'Student')], max_length=10, null=True),
        ),
    ]
